# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

# Expose the port your app will run on
EXPOSE 5500

# Define the command to start your Express app
CMD ["node", "app.js"]
